name: ScavengeHunt
main: io.github.michelfaria.scavengehunt.ScavengeHunt
version: 1.0
api-version: 1.13
commands:
  createzone:
    description: Creates a Scavenge Hunt zone
    usage: /<command> <x1> <y1> <z1> <x2> <y2> <z2> <ox> <oy> <oz> <name> <world>
    permission: scavengehunt.admin
  scavstart:
    description: Starts the game
    usage: /<command> <time>
    permission: scavengehunt.admin
  scavstop:
    description: Stops the game
    usage: /<command>
    permission: scavengehunt.admin
  warp:
    description: Warp to a zone
    usage: /<command> <zone-name>
    permission: scavengehunt.user
  zones:
    description: List zones
    usage: /<command>
    permission: scavengehunt.user
permissions:
  scavengehunt.*:
    description: Gives access to all ScavengeHunt commands
    children:
      scavengehunt.admin: true
      scavengehunt.user: true
  scavengehunt.admin:
    description: Gives access to admin commands
    default: op
  scavengehunt.user:
    description: Gives access to user commands
    default: true